name: main Build Push Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_and_push_frontend:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Build and push frontend
        uses: docker/build-push-action@v5
        with:
          context: ./client
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/coding-theory-calculator-frontend:${{ github.sha }}
          
  build_and_push_backend:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Build and push backend
        uses: docker/build-push-action@v5
        with:
          context: ./server
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/coding-theory-calculator-backend:${{ github.sha }}
      
  deploy:
    needs: [build_and_push_frontend, build_and_push_backend]
    environment: 
      name: Production
      url: https://coding-theory-calculator.billylee.me
    runs-on: ubuntu-latest
    steps:
    - name: Installing SSH key
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.DROPLET_SSH_KEY }}
      
    - name: Deploy to DigitalOcean Droplet
      run: |
        ssh -o StrictHostKeyChecking=no root@${{ secrets.DROPLET_IP }} << 'EOF'
          cd /root/coding-theory-calculator
          echo FRONTEND_IMAGE_TAG=${{ secrets.DOCKER_USERNAME }}/coding-theory-calculator-frontend:${{ github.sha }} > .env
          echo FRONTEND_IMAGE_TAG=${{ secrets.DOCKER_USERNAME }}/coding-theory-calculator-backend:${{ github.sha }} >> .env
          docker compose pull
          docker compose up -d
        EOF
